#!/usr/bin/env bash
# Script that configures an Ubuntu server

# Create backup of original hosts file
cp /etc/hosts ~/hosts.new

# configure localhost resolves to 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

# configure facebook.com resolves to 8.8.8.8
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace old hosts file with new one
cp -f ~/hosts.new /etc/hosts
